spring.application.name=backend

# Banco de Dados Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/estudadb
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Configurações do JWT (Chave com pelo menos 256-bit em Base64)
estudamais.jwt.secret=9a4f2c8d3e1b7a6f5c4d3b2a1e0f9b8a7c6d5e4f3a2b1c0e9d8c7b6a5f4e3d2c
estudamais.jwt.expiration=86400000

# Google Gemini API Config
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
gemini.api.key=SUA_CHAVE_REAL_DO_GEMINI_AQUI

# Configuração de Filas RabbitMQ
rabbitmq.queue.welcome=user.welcome.queue
rabbitmq.exchange.internal=internal.exchange
rabbitmq.routing-key.welcome=welcome.routing.key