spring.application.name=backend

# Banco de Dados Postgres
spring.datasource.url={SPRING_DATASOURCE_URL}
    spring.datasource.username={SPRING_DATASOURCE_USERNAME}
spring.datasource.password={SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Configurações do JWT
estudamais.jwt.secret=9a4f2c8d3e1b7a6f5c4d3b2a1e0f9b8a7c6d5e4f3a2b1c0e9d8c7b6a5f4e3d2c
estudamais.jwt.expiration=86400000

#limitando o tamanho dos arquivos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

