spring.application.name=backend

# Banco de Dados Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/estudadb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Configurações do JWT
estudamais.jwt.secret=9a4f2c8d3e1b7a6f5c4d3b2a1e0f9b8a7c6d5e4f3a2b1c0e9d8c7b6a5f4e3d2c
estudamais.jwt.expiration=86400000

# Configuração de Filas RabbitMQ
rabbitmq.queue.welcome=user.welcome.queue
rabbitmq.exchange.internal=internal.exchange
rabbitmq.routing-key.welcome=welcome.routing.key